name: kEconomy
version: '${project.version}'
main: fr.kirosnn.keconomy.kEconomy
api-version: 1.13
softdepend:
  - Vault
  - Treasury
  - PlaceholderAPI
authors:
  - kirosnn
description: ${project.description}
folia-supported: true
